version: "3"
services:

  init-guacamole-db:
    image: guacamole/guacamole:latest
    command: ["/bin/sh", "-c", "test -e /init/initdb.sql && echo 'init file already exists' || /opt/guacamole/bin/initdb.sh --mysql > /init/initdb.sql" ]
    volumes:
      - dbinit:/init    

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - dbinit:/docker-entrypoint-initdb.d        
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: ${MYSQL_USER:-guacdb}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - init-guacamole-db

  guacd:
    image: guacamole/guacd:latest
    restart: unless-stopped

  min:
    image: min:latest
    restart: unless-stopped
    ports:
      - "5903:5901"
      - "6903:6901"

  guac:
    image: guacamole/guacamole:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: ${MYSQL_USER:-guacdb}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - mysql
      - guacd
      - min

volumes:
  dbinit:
    driver: local
  dbdata:
    driver: local
